pool:
  vmImage: Ubuntu-16.04

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.15.0

  - script: yarn install
    displayName: Install dependencies

  - script: yarn lint && yarn type-check
    displayName: Running tests

  - script: yarn build
    displayName: Build application
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
