pool:
  vmImage: Ubuntu-16.04

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.15.3

  - script: yarn install --frozen-lockfile
    displayName: Install dependencies

  - script: yarn lint
    displayName: Lint source code

  - script: yarn copy:paste:detector
    displayName: Copy/Paste detector

  - task: PublishPipelineArtifact@0
    displayName: Publish jscpd HTML report
    condition: failed()
    inputs:
      artifactName: 'CopyPasteDetectorReport'
      targetPath: 'dist/jscpd-report.html'

  - script: yarn compile
    displayName: Compile source code

  - script: |
      yarn build:visual
      yarn test:visual
    displayName: Run visual regression tests
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - task: PublishPipelineArtifact@0
    displayName: Publish visual regression HTML report
    condition: failed()
    inputs:
      artifactName: 'VisualRegressionResults'
      targetPath: 'test/visual/backstop_data'

  - task: PublishTestResults@2
    displayName: Publish visual regression test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: test/visual/backstop_data/ci_report/xunit.xml

  - script: yarn build
    displayName: Build application for production
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - script: yarn netlify deploy --prod
    displayName: Production deploy to Netlify
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
      NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)

  - script: yarn netlify deploy
    displayName: Branch deploy to Netlify
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
      NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
