pool:
  vmImage: Ubuntu-16.04

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.15.3

  - script: yarn install
    displayName: Install dependencies

  - script: yarn lint && yarn type-check
    displayName: Running tests

  - script: yarn build
    displayName: Build application
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'echooff.de'
      targetPath: 'public'

  - script: yarn netlify deploy --prod
    displayName: Production deploy to Netlify
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    env:
      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
      NETLIFY_SITE_ID: $(NETLIFY_SITE_ID)
