[build]
  command = "npm run build"
  publish = "public"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "https://echooff.de/*"
  to = "https://www.echooff.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.echooff.de/*"
  to = "https://www.echooff.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__api"
  status = 200

# https://github.com/netlify/netlify-plugin-gatsby/issues/219#issuecomment-1018321552
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
