[build]
  publish = "public"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs10.x" }

[[redirects]]
  from = "https://echooff.de/*"
  to = "https://www.echooff.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.echooff.de/*"
  to = "https://www.echooff.dev/:splat"
  status = 301
  force = true
