---
name: "npm install"
description: 'Setup Node.js and makes a "npm install"'

runs:
  using: "composite"
  steps:
    - name: Download Node.js
      uses: volta-cli/action@v4
    - name: Install dependencies
      run: npm clean-install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
