---
when:
    - event: [push, manual]

steps:
    - name: install
      image: node:22.14.0
      environment:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      commands:
          - npm clean-install

    - name: build application
      image: node:22.14.0
      commands:
          - npx rust-just build

    - name: build container image
      image: woodpeckerci/plugin-docker-buildx:5.2.2
      settings:
          dry-run: true
          dockerfile: Dockerfile
          platforms: linux/amd64
