---
when:
    - event: push

steps:
    - name: install
      image: node:24.3.0
      environment:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      commands:
          - npm clean-install

    - name: build application
      image: node:24.3.0
      commands:
          - npx rust-just build

    - name: build container image
      image: woodpeckerci/plugin-docker-buildx:6.0.1
      settings:
          dry-run: true
          dockerfile: Dockerfile
          platforms: linux/arm64
