---
when:
    - event: manual

steps:
    - name: publish-docker-container
      image: woodpeckerci/plugin-docker-buildx:5.2.1
      settings:
          repo:
              from_secret: repository
          registry:
              from_secret: registry
          dockerfile: Dockerfile
          platforms: linux/amd64
          tags: latest
          username:
              from_secret: username
          password:
              from_secret: access_token

depends_on:
    - test
