---
when:
    - event: manual

steps:
    - name: build
      image: node:24.0.1
      environment:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
          GITHUB_API_BASE_URL: ""
          GITHUB_LOGIN: ""
          GITHUB_API_TOKEN_FILE: ""
      commands:
          - npm clean-install
          - npx rust-just build

    - name: publish-container-image
      image: woodpeckerci/plugin-docker-buildx:6.0.1
      settings:
          repo:
              from_secret: repository
          registry:
              from_secret: registry
          dockerfile: Dockerfile
          platforms: linux/arm64
          tags:
              - latest
              - ${CI_COMMIT_SHA}
          username:
              from_secret: username
          password:
              from_secret: access_token

depends_on:
    - test
