---
when:
    - event: [push, manual]

steps:
    - name: install
      image: node:25.0.0
      commands:
          - npm clean-install

    - name: test
      image: node:25.0.0
      commands:
          - npx just test
          - npx just build
