---
when:
    - event: [push, manual]

steps:
    - name: install
      image: node:24.3.0
      environment:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      commands:
          - npm clean-install

    - name: test
      image: node:24.3.0
      commands:
          - npx rust-just test
