---
when:
    - event: push

steps:
    - name: install
      image: node:24.12.0
      commands:
          - npm clean-install

    - name: test
      image: node:24.12.0
      commands:
          - npx just test
          - npx just build
