---
when:
    - event: push

steps:
    - name: install
      image: node:24.13.0
      commands:
          - npm clean-install

    - name: test
      image: node:24.13.0
      environment:
          GITHUB_API_BASE_URL: https://api.github.com
          GITHUB_TOKEN: fake_token_for_testing
          GITHUB_LOGIN: fake_user
      commands:
          - npx just test
