---
when:
    - event: [push, cron, manual]

steps:
    - name: install
      image: node:25.7.0
      commands:
          - npm clean-install

    - name: test
      image: node:25.7.0
      environment:
          GITHUB_API_BASE_URL: https://api.github.com
          GITHUB_TOKEN: fake_token_for_testing
          GITHUB_LOGIN: fake_user
      commands:
          - npx just test
