name: CI

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * MON,THU' # At 00:00 on Monday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detector
      - name: Compile source code
        run: npm run compile
      - name: Run unit tests
        run: npm run test:unit:coverage
      - name: Build application for visual regression and e2e tests
        run: npm run build:visual
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Run e2e tests
        continue-on-error: true
        run: npm run test:e2e:ci
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_BUILD_ID: ${{ github.run_id }}
          BROWSERSTACK_PROJECT_NAME: ${{ secrets.BROWSERSTACK_PROJECT_NAME }}
      - name: Run visual regression tests
        run: npm run test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Build application for production
        run: npm run build
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: target/coverage/clover.xml
      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          netlify-config-path: './netlify.toml'
          alias: ${{ github.head_ref }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.deploy-to-netlify.outputs.deploy-url }}
          temporaryPublicStorage: true
      - name: Run accessibility tests
        run: npm run test:a11y -- ${{ steps.deploy-to-netlify.outputs.deploy-url }}
      - name: Quickmetrics
        uses: screendriver/quickmetrics-action@v1
        with:
          name: echooff.dev
          api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
          dimension: deployment
