name: CI

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * MON,THU' # At 00:00 on Monday and Thursday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detector
      - name: Compile source code
        run: npm run compile
      - name: Run unit tests
        run: npm run test:unit:coverage
      - name: Build application for visual regression and e2e tests
        run: npm run build:visual
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Run visual regression tests
        run: npm run test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Build application for production
        if: github.ref == 'refs/heads/master'
        run: npm run build
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: target/coverage/clover.xml
      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.deploy-to-netlify.outputs.deploy-url }}
          temporaryPublicStorage: true
