name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Check source code
        run: |
          yarn lint
          yarn copy:paste:detector
      - name: Compile source code
        run: yarn compile
      - name: Run unit tests
        run: yarn test:unit:coverage
      - name: Build application for visual regression and e2e tests
        run: yarn build:visual
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Run e2e tests
        run: yarn test:e2e
      - name: Run visual regression tests
        run: yarn test:visual
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Build application for production
        if: github.ref == 'refs/heads/master'
        run: yarn build
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: target/coverage/clover.xml
      - name: Production deploy to Netlify
        if: github.ref == 'refs/heads/master'
        run: yarn netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Lighthouse Audit
        if: github.ref == 'refs/heads/master'
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://www.echooff.dev
          temporaryPublicStorage: true
