name: Vercel preview

on: workflow_dispatch

jobs:
    deploy-preview-to-vercel:
        name: Deploy preview to Vercel
        runs-on: ubuntu-latest
        env:
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        steps:
            - name: Checkout code
              uses: nschloe/action-cached-lfs-checkout@v1
            - name: Setup Node.js
              uses: ./.github/actions/setup-nodejs
            - name: Pull Vercel Environment Information
              run: npx vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
            - name: Build Project Artifacts
              run: npx vercel build --token=${VERCEL_TOKEN}
            - name: Deploy Project Artifacts to Vercel
              run: npx vercel deploy --prebuilt --token=${VERCEL_TOKEN}
